### ISSUE TITLE
Arrows on numeric keypad do not work for task prio changes

### ISSUE THREAD

**Issue by chipbite** [benrhughes/todotxt.net#278]
TC: 
Select task. Press alt+up or down using keypad (naturally w/o numlock on). 
Expected: Task prio change. Actual: No result.

PS Awesome release today!

**Comment by mjdescy** [comment]
Ah! I just got a tenkeyless keyboard and was thinking that I haven't used the number pad as arrow keys since the '90s!

The number pad arrow keys aren't translated into Up/Down/Left/Right arrow keys when NumLock is off. I'll have to put logic in to support that. Just wondering, are those keys working to navigate the list?

I'll grab my old keyboard and bang out a fix for this in the next week or so. I don't have my dev machine at the moment.

**Comment by chipbite** [comment]
I can confirm that yes, the keys are working to navigate the list. 
This seems to just affect the task prio shortcut.

**Comment by mjdescy** [comment]
I looked into this. Apparently the NumPad keys can't take modifiers in key bindings, which is preventing me from enabling this feature.

**Comment by chipbite** [comment]
Wouldn't have guessed that it wasn't possible, bummer! 
Is that definite or was it quick pass results? 
Anyway, low prio on this, nice to have.
