### ISSUE TITLE
Feedback on chosen filter

### ISSUE THREAD

**Issue by chipbite** [benrhughes/todotxt.net#279]
With all the filters it would be good to see which one Ive chosen.

Could be:
- Allow filters to be named, add box for that. Show filter name in window titlebar for instance.
- SHow filter text in titlebar.
- ... ?

**Comment by mjdescy** [comment]
I would prefer an optional status bar, like in TodoTxtMac.

![](https://mjdescy.github.io/TodoTxtMac/images/todotxtmac-screenshot.png)

**Comment by robertvanbregt** [comment]
I second the status bar.

**Comment by muteboy** [comment]
Thirded

**Comment by flight16** [comment]
What an inspiring status bar.  Fourthed.

**Comment by sckaushal** [comment]
I'm a pretty regular user of Todotxt.net, thank you for building this. :) 
I'm taking a stab at implementing this feature.  The feature is not complete since I'm new to XAML and Git, but the filter and sort status bar look like the image below.  The code so far is committed in my clone of the repo, if anyone's interested. 
If we're going to make the status bar optional, what's the best place to allow users to hide/show it? Most apps would have a 'View' menu item.  
Also, any pointers to the cleanest way to get the task summary information for the status items? 


![image](https://cloud.githubusercontent.com/assets/9510466/16920876/f50263d8-4d41-11e6-84e0-159035fcbbfb.png)

**Comment by mjdescy** [comment]
The screenshot looks great!  I recommend adding a checkbox to the options window, just to get it done the easiest way. 

A View menu sounds like a great enhancement down the line. Other view options (grouping, word wrap, etc.) could be moved to it, and have keyboard shortcuts for toggling. That's a bigger change, however.

**Comment by sckaushal** [comment]
Thank you :). I'll toggle it off the options for now.

**Comment by mjdescy** [comment]
@sckaushal I am playing with your build. I noticed a couple bugs:

1. The status bar will say "Filter: None" at startup, but then it will say "Filter #0" after a filter preset is applied and then cleared.

2. [This is a bug in Todotxt.net, not your status bar-related modifications.] The filter preset number in the status bar, and the selected filter preset in the filter menu, does not get reset when the user goes to the "Define filters" window and modifies the "Currently active filter" box and clicks "OK".

**Comment by sckaushal** [comment]
@mjdescy  Thank you for taking a look.
1. I'll fix this by changing the property that the status bar is hooked up to into an integer representing the active filter. It'll then be consistent between startup and reset. This can also be used as a basis for point 2. 

2. Shall I create a bug for this?  If the active filter number in the view model is reset when the active filter is modified, then it will automatically reset the status bar.

**Comment by sckaushal** [comment]
@mjdescy  I think the implementation of the optional status bar is complete. Can you please take a look when you get a chance and let me know if there are any bugs or design mistakes?
This is my repo: https://github.com/sckaushal/todotxt.net
Some points:
The logic implemented for each item is:
a. Tasks: m - Only filtered tasks, both complete and incomplete.
	    of
		n - All tasks in file, both complete and incomplete
b. Incomplete: All filtered tasks  where t.Completed = false.
c. Due Today: All filtered incomplete tasks where due date = today.
d. Overdue: All filtered incomplete tasks where due date < today, ignoring filters. 

Also, since the status bar is a clone of the TodoTxtMac bar, what would be the best place to mention that? (Since TodoTxtMac is your project, you'd be the best person to answer that :)) 

![image](https://cloud.githubusercontent.com/assets/9510466/17338120/87a08b20-5918-11e6-9ea0-9646e42efee6.png)

**Comment by mjdescy** [comment]
@sckaushal Thanks so much for coding this! I love it! 

The code looks fine. I found one minor thing to fix: please add a space before the filter number.

(By the way, you don't have to mention TodoTxtMac anywhere in the code. :-))

You will have to issue a pull request to get this code into the main repo, so we can do a release. One thing about GitHub is that you can only do one pull request per branch, so you probably should have created a temporary branch off of "dev" before committing your work. This is not a big deal, though. I made that mistake in my first commit to this project. 

I recommend backing up your code, then moving your commits to a new branch (see [StackOverflow ](http://stackoverflow.com/questions/1628563/move-the-most-recent-commits-to-a-new-branch-with-git) for instructions). You can even be fancy and [squash your commits down to a single commit](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before sending the pull request. Let me know if you need help with that after fixing the "space before filter number" issue.

**Comment by sckaushal** [comment]
@mjdescy  Thank you for the review and positive comments. Todotxt.net is how I manage most of my bills and chores, so I'm glad I could help out. 
  I'll use your instructions to issue a pull request over the weekend.

**Comment by sckaushal** [comment]
@mjdescy  I have issued a pull request, please take a look. I did rebase the commits into a single commit, but my pull request doesn't seem to reflect it. Hope that's ok. Thanks!
