### ISSUE TITLE
Support for future tasks

### ISSUE THREAD

**Issue by metbril** [benrhughes/todotxt.net#286]
Support for tasks that have a start date in the future / with a treshold.

See also:
https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#future-tasks

Support implies:
- setting, increasing, decreasing, removing (like due dates)
- filtering
- sorting

Please note that the `s:` key is not part of the formal specifications

**Comment by robertvanbregt** [comment]
Support implies:

* setting, increasing, decreasing, removing (like due dates)
* filtering
* sorting

**Comment by mjdescy** [comment]
Threshold date uses the `t:` key, not `s:`. The [TodoTxtWin library](https://github.com/mjdescy/TodoTxtWin) supports parsing threshold date. If I integrate that code with Todotxt.net, we would only have to add front-end support.

**Comment by lalthomas** [comment]
+1

**Comment by paullemmens** [comment]
We discussed this also in #224. Unfortunately, Ben seems to be favoring to only support the basic todo.txt format (without the addons that implement future dates using thresholds). Perhaps this provides new impetus, but let's wait and see what Ben says.
\

**Comment by flight16** [comment]
This is also very important to me, to the point that I can't use todotxt.net without it.  Start (threshold) dates are a key tool of many GTDers.  As discussed in #224 they are also implemented in several other todo.txt clients.  It would also allow todotxt.net to be used as a tickler file.

I see the case for supporting the basic todo.txt format by default, but surely there could be an opt-in "Enable threshold dates" checkbox.  As mentioned in #224, adding such metadata is entirely within the todo.txt spec:

> Note that the t:YYYY-MM-DD doesn't modify the todo.txt format. It uses the specified way of adding metadata (see https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#add-on-file-format-definitions) 

Wondering if @benrhughes 's thoughts have changed any and would be willing to accept a pull request.

**Comment by benrhughes** [comment]
It seems like a popular request, so yes, I'd take a pull request.

Unfortunately a change in jobs means that I 1) no longer have ready access
to a Windows machine and 2) don't actually use todotxt.net. So merging,
testing and releasing the change may take a while (I'll have to get my
hands on a copy of Windows and run up a VM).

Cheers,

Ben

**Comment by flight16** [comment]
@benrhughes Thanks.  I'm not sure if I'll be able to find the time, but if I do I'll send a request.

@mjdescy , is @benrhughes on-board with using your TodoTxtWin back-end?  What work do you imagine is involved?

**Comment by chipbite** [comment]
I also second this request, future tasks is a great thing.

**Comment by mjdescy** [comment]
@flight16 I haven't really asked @benrhughes about using my TodoTxtWin library. 

I would have pushed harder for adopting the TodoTxtWin library, but I have been working on a couple other todo.txt-related apps (on Apple platforms, nothing public just yet). Originally I wanted to code my own TodoTxtWin front end that is 100% MVVM compliant. I am not really a WPF developer, so the front-end stuff has been challenging for me--at least when I try to code everything with MVVM. I kind of stalled out and decided to jump back to the Apple platforms I prefer coding on for a while. My last commit on TodoTxtWin was a couple months ago; I fixed a number of bugs I discovered when trying to wire up a WPF UI, which is still not in any state to push out to the world.

At one point I tried replacing the todotxt.net library with TodoTxtWin on my local repo. I didn't finish--mostly because I couldn't commit a bunch of time to it, and I wasn't sure if some of TodoTxtWin's features would be things Ben wanted in todotxt.net. 

Some great benefits of TodoTxtWin are more efficient regex, more stringent todo.txt format compatibility, support for threshold dates, lots of unit tests, and better encapsulation of functionality. 

I still am a daily todotxt.net user, and plan to contribute more to todotxt.net and TodoTxtWin in the future, mostly after my more immediate project is finished.

**Comment by benrhughes** [comment]
I don't have any major concerns about replacing the file interaction code.
If we do do it, it might be nice to do it as a 4.0, and release a beta for
a few months to try and catch any migration bugs.

As I mentioned earlier, unfortunately I'm not in a position to contribute
much myself right now - I can't even install software on the only Windows
machine I have access to. I'll try and get that sorted soon so that I can
get some of the more serious recently supported bugs sorted out.

Cheers,

Ben

**Comment by bttrx** [comment]
@benrhughes Any update on this?

**Comment by woosting** [comment]
I hate to be "that guy" that "bumps" the ages old request.. but; any light at the horizon with respect to the "t:<date>" threshold filtering to be implemented?

I'm sure there's  _someone_ out there able to code and provide a pull request for our Windows-less Ben to merge?

It shouldn't be too hard, as I suppose it is fairly similar to the "due:<date>" filter implementation (sadly my code-fu is to weak to contribute in the form of actual code myself).

**Comment by mjdescy** [comment]
I would like to code this feature, but I am up to my ears in requests on my Mac and iOS clients.

**Comment by woosting** [comment]
Thanks @mjdescy for replying! Yah.. I can imagine you drowning in those; *popular* elegant program you've build)! I'll wait my turn (or learn to code in between ^^). Keep up the good work!

**Comment by geirkairam** [comment]
I work with this feature on other devices and I really miss it in this app. So I implemented the function last week. It works well for me. Would you accept a pull request although I did not change the whole text parsing to "TodoTxtWin library" as you discussed above?

**Comment by benrhughes** [comment]
Yep, I'd happily take that PR :)

**Comment by geirkairam** [comment]
Any thoughts on my PR #332 ?

**Comment by benrhughes** [comment]
Sorry, life has been crazy. I'm reviewing the PR now and am about to merge it.
