### ISSUE TITLE
Feature: New setting 'Show hidden tasks' (default = yes)

### ISSUE THREAD

**Issue by bttrx** [benrhughes/todotxt.net#307]
@benrhughes It's probably against todotxt.net's lean approach, but can we have a setting to _not_ show tasks containing 'h:1', instead of using filters?

**Comment by benrhughes** [comment]
I don't have any philosophical reason against this, though I don't feel any motivation to implement it myself (sorry!). If someone submits a pull request in the future I'll accept it.

**Comment by prakhargahlot** [comment]
Since this change has gone in, shouldn't there be some documentation about "Hidden Tasks"? I saw a new option "Show Hidden Tasks", but I had to fumble my way to this thread to know how to make one.

I would have loved to contribute to it, but I don't know Windows programming, or have the full context about "Hidden Tasks". Perhaps I can make a new issue to start things off, @benrhughes ?

**Comment by benrhughes** [comment]
Hi,
Yes, it should be on the help screen.

However, I really think that we need a wiki page that is a bit more
comprehensive than the current screen - we have so many features now and a
bunch of them aren't properly covered on that screen.

You're welcome to start that wiki page if you'd like (no programming
knowledge needed :)) or create an issue and I'll try to get to it soonish.

Cheers,

Ben
