### ISSUE TITLE
Can't build new version; stuck on CreateInstaller.bat part of Release Process

### ISSUE THREAD

**Issue by mjdescy** [benrhughes/todotxt.net#318]
@benrhughes ,

I would like to draft a new release with the cool status bar feature that @sckaushal added. I cannot get past the CreateInstaller.bat part of the [Release Process](https://github.com/benrhughes/todotxt.net/wiki/Release-Process). I get various build errors that do not arise when I build the executable within Visual Studio. When I clear up the first one, more arise. Are you able to help?

**Comment by benrhughes** [comment]
Hi Mike,
It looks like @sckaushal has used some C# 6 language features (like 'using static'). The current installer script uses the .NET 4.0 version of msbuild, which is why it's failing. I've changed it to use the .NET 4.6 msbuild, but am now running into Inno errors - I'll try to get them sorted now.

**Comment by benrhughes** [comment]
Should be good now. Just FYI sometimes the Inno part of the script fails the first time - running it again usually works. No idea why (the installer + script was a contrib that I've never fully gotten across).

**Comment by frou** [comment]
Do you guys have a minimum dev environment requirement in mind for todotxt.net?

I was just taking a look at the project and can't build it in VS2013. This seems purely down to a few uses of the C# 6 "nameof" operator. While a perfectly valid convenience feature to use, I'm not sure it's worth hiking the minimum requirement to build to VS2015.

**Comment by benrhughes** [comment]
I'm pretty sure you can install .net 4.6 with vs2013

**Comment by frou** [comment]
Well... it seems that adding the `Microsoft.Net.Compilers` package using NuGet allows VS2013 to compile C# 6, even though the `nameof` operator still gets the red squiggly underline in the editor, and I don't have .NET 4.6 installed either.

Can't say I fully understand the moving parts of the stack - my .NET knowledge is pretty rusty. Thanks for the quick push in the right direction!

**Comment by sckaushal** [comment]
Hi Ben,
Since I don't recall using many.NET 4.6 specific features, I can remove
them and create a pull request. This would lower the bar to use and
contribute.What do you think?
Kaushal

On Sun, 11 Dec 2016 at 8:32 PM, Duncan Holm <notifications@github.com>
wrote:

Well... it seems that adding the Microsoft.Net.Compilers package using
NuGet allows VS2013 to compile C# 6, even though the nameof operator still
gets the red squiggly underline in the editor, and I don't have .NET 4.6
installed either.

Can't say I fully understand the moving parts of the stack - my .NET
knowledge is pretty rusty. Thanks for the quick push in the right direction!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/benrhughes/todotxt.net/issues/318#issuecomment-266279496>,
or mute the thread
