### ISSUE TITLE
New key binding interferes with "New Comment"

### ISSUE THREAD

**Issue by cribb** [benrhughes/todotxt.net#356]
Hi,

I have used todotxt.net for years and love the application better than any other todo.txt app I've tried. You folks do a fantastic job with the app. Thank you for that.

I'm logging an issue, because--at least in Windows 7--the new version of todotxt.net seems to require a new key-binding to bring up the interface, i.e. "Ctrl-Alt-M", whereas the old key-binding used "Win-Alt-T".

Default key-bindings for both Word and Google Docs, Sheets, etc. uses "Ctrl-Alt-M" to insert a new comment for a document, functionality a writer and editor needs handy every day. Every time I try to insert a new comment, todotxt.net's interface dutifully appears from my taskbar.

Is there some way to change this back to the prior binding within my installation?

Again, thanks to the group for your work. I love the productivity your app affords me.

Best,
Jeremy

**Comment by benrhughes** [comment]
Hi Jeremy,
It was changed from win-alt-t because apparently that conflicted with a
display setting for a lot of Windows 10 people. Trying to find a global
shortcut that doesn't conflict is proving to be a royal pain.

In the future I think we should allow the user to choose their own
shortcut. For now, as a workaround, disabling 'minimise to tray' should
also disable the shortcut.

If you really need the tray minimisation, the only way to go back to the
old shortcut is to install an older version of the app.

Cheers,

Ben
