### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by shulist** [benrhughes/todotxt.net#376]
@benrhughes There have been many references in this issue log to the "**next release**" of TDT. When exactly is the next release planned for? Is there some overall plan of when this might occur and what might be included as far as:

1. Bugs (18 currently tagged),
1. Features (18 currently tagged) and/or
1. Maybe Someday  (5 currently tagged).

Recognizing that as of today there are only 7 issues tagged as "**Ready For Work**" it would seem that there is some planning effort required to bridge the gap between that and outstanding issues as shown in the list above.
While I am useless at programming I could add some effort into documentation (or the wiki), if that is required, as it seems the documentation for TDT is somewhat in the wiki and partly in these issues.
I really appreciate the work that has gone into TDT thus far and would like to see it moved to the next level.

**Comment by benrhughes** [comment]
To be honest there isn't really a plan - it's more about when I find the time to create and test the release. 

As for what's included, it will be all the pull requests merged since the last release, which you can find with this query: https://github.com/benrhughes/todotxt.net/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+closed%3A2017-09-23..2019-01-20+
As you can see, there's not a whole lot waiting to be released. I usually hold off until it feels like there's enough in there to justify the effort.

In terms of help, I'm always happy with doco contributions. The other thing that would be more useful (to me, at least) would be beta testing the next release. One of the issues I have is that there are a lot of features that I don't use, so I don't always notice bugs before I let the release out into the wild. 











---- On Sun, 20 Jan 2019 08:51:22 +1100 shulist <mailto:notifications@github.com> wrote ----




https://github.com/benrhughes There have been many references in these issues to the "next release" of TDT. When exactly is the next release planned for? Is there some overall plan of when this might occur and what might be included as far as  bugs, features, improvements etc.?

While I am useless at programming I could add some effort into documentation (or the wiki), if that is required, as it seems the documentation for TDT is only in these issues.

**Comment by shulist** [comment]
@benrhughes 
> beta testing the next release
I'd be happy to do anything I can to assist in this area.

> what's included

I'd think you should also look at items 1-3 in my original post above?

**Comment by benrhughes** [comment]
I generally only deal with github via email, so didn't notice your edit which added the list - sorry about that.

You're correct that the issues need to be tidied up, but you may not be pleased with how I'll do it.

I started working on the app 8 years ago, and haven't used it myself for about 5 years. To my mind, it's well past time to transition it to maintenance mode. While I'm more than happy for people to contribute bug fixes, at this point I'm going to freeze new features. There is only so much that a minimalist app can do.

With that said, I'll put some time in this month to get a beta release out and tidy up the issues.

Cheers,

Ben


---- On Sat, 09 Feb 2019 09:20:53 +1100 notifications@github.com wrote ----

@benrhughes

beta testing the next release
I'd be happy to do anything I can to assist in this area.

what's included

I'd think you should also look at items 1-3 in my original post above?

**Comment by benrhughes** [comment]
@shulist there is a new beta release here : https://github.com/benrhughes/todotxt.net/releases/tag/3.3.1-beta

Please let me know if you find any issues.

Cheers,

Ben
