### ISSUE TITLE
[Feature request] Option to maintain priority in completed tasks

### ISSUE THREAD

**Issue by pig-cop** [benrhughes/todotxt.net#412]
If I set a task as completed the priority is cleared.
Any chance to add an option to maintain the priority?
It is useful for my case scenario to know the priority of past completed tasks.

**Comment by benrhughes** [comment]
Hi,

Although this is a common request, I believe that it's outside of the todo.txt format spec (https://github.com/todotxt/todo.txt) and so, in order to maintain compatability with other todo.txt apps, it won't be added. 



Cheers,



Ben





---- On Sat, 26 Sep 2020 01:02:35 +1000 pig-cop <notifications@github.com> wrote ----





If I set a task as completed the priority is cleared.
 Any chance to add an option to maintain the priority?
 It is useful for my case scenario to know the priority of past completed tasks.

**Comment by pig-cop** [comment]
I understand your decision, but considering that clearing or not clearing the priority are arbitrary out of spec actions (both are valid) it does make sense to have an option to enable or disable this behaviour.

**Comment by fleapower** [comment]
Portable version which retains priority at https://github.com/fleapower/todotxt.net/.  It is based on [jdckr's fork](https://github.com/jdckr/todotxt.net).
